# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dong' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry', '~> 1.1.0'
  #source ‘https://github.com/CocoaPods/Specs.git’
  # platform :ios, '9.0'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SDWebImage', '~> 4.2.3'
  pod 'MJRefresh', '~> 3.1.15.1'
  # Pods for Dong

  target 'DongTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DongUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
