# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dongqiu' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Masonry'
    pod 'SwiftTheme'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Kingfisher'
    pod 'HandyJSON', '5.0.0-beta'
end
